# Generated by Django 5.2.8 on 2026-04-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback', '0003_remove_feedback_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='approved',
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('B', 'Blocked')], default='P', max_length=2),
        ),
    ]
